version: "3.8"

services:
  app:
    container_name: next-app
    pull_policy: build
    build: .
    image: rafadev-site
    ports:
      - "${APP_PORT}:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped
