version: "3.8"

services:
  app:
    container_name: next-app
    build: .
    image: rafadev-site
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped
