import { ImagesSrc } from "@/types/slider";

export const imagesSrc: ImagesSrc[] = [
  {
    url: "/skills/postgres.svg",
    alt: "Postgresql",
    style: "md:max-h-[40%] md:max-w-[40%] max-h-[10%] max-w-[10%]",
    description: "Banco de dados Postgresql",
    category: "backend",
  },
  {
    url: "/skills/docker.svg",
    alt: "Docker",
    style: "md:max-h-[60%] md:max-w-[60%] max-h-[10%] max-w-[10%]",
    description: "Containização Docker",
    category: "devops",
  },
  {
    url: "/skills/prisma.svg",
    alt: "Prisma",
    style: "md:max-h-[50%] md:max-w-[50%] max-h-[10%] max-w-[10%]",
    description: "Prisma ORM",
    category: "backend",
  },
  {
    url: "/skills/nodejs.svg",
    alt: "Node.js",
    style: "md:max-h-[30%] md:max-w-[30%] max-h-[10%] max-w-[10%]",
    description: "Ambiente javascript runtime",
    category: "backend",
  },
  {
    url: "/skills/tailwindcss.svg",
    alt: "tailwindcss",
    style: "md:max-h-[50%] md:max-w-[50%] max-h-[10%] max-w-[10%]",
    description: "Framework CSS",
    category: "frontend",
  },
  {
    url: "/skills/react.svg",
    alt: "React",
    style: "md:max-h-[20%] md:max-w-[20%] max-h-[10%] max-w-[10%]",
    description: "Biblioteca de criação de interfaces",
    category: "frontend",
  },
  {
    url: "/skills/nextjs.svg",
    alt: "NextJS",
    style: "md:max-h-[40%] md:max-w-[40%] max-h-[10%] max-w-[10%]",
    description: "Framework para ReactJS",
    category: "frontend",
  },
  {
    url: "/skills/jest.svg",
    alt: "Jest",
    style: "md:max-h-[40%] md:max-w-[40%] max-h-[10%] max-w-[10%]",
    description: "Biblioteca para testes automatizados",
    category: "frontend",
  },
  {
    url: "/skills/github.svg",
    alt: "Github",
    style: "md:max-h-[30%] md:max-w-[30%] max-h-[10%] max-w-[10%]",
    description: "Plataforma de repositorios",
    category: "devops",
  },
  {
    url: "/skills/nginx.svg",
    alt: "Nginx",
    style: "md:max-h-[30%] md:max-w-[30%] max-h-[10%] max-w-[10%]",
    description: "Webserver",
    category: "devops",
  },
  {
    url: "/skills/ubuntu.svg",
    alt: "Ubuntu",
    style: "md:max-h-[30%] md:max-w-[30%] max-h-[10%] max-w-[10%]",
    description: "Sistema operacional Unix",
    category: "devops",
  },
  {
    url: "/skills/typescript.svg",
    alt: "Typescript",
    style: "md:max-h-[30%] md:max-w-[30%] max-h-[10%] max-w-[10%]",
    description: "Superset para javascript",
    category: "linguagem",
  },
  {
    url: "/skills/cloudflare.svg",
    alt: "Cloudflare DNS",
    style: "md:max-h-[50%] md:max-w-[50%] max-h-[10%] max-w-[10%]",
    description: "Plataforma de gerenciamento DNS e Storage",
    category: "devops",
  },
  {
    url: "/skills/digitalocean.svg",
    alt: "Digital Ocean Cloud",
    style: "md:max-h-[70%] md:max-w-[70%] max-h-[10%] max-w-[10%]",
    description: "Hospedagem cloud",
    category: "devops",
  },
  {
    url: "/skills/datadog.svg",
    alt: "Datadog Monitoring",
    style: "md:max-h-[70%] md:max-w-[70%] max-h-[10%] max-w-[10%]",
    description: "Plataforma de monitoramento de aplicações",
    category: "devops",
  },
  {
    url: "/skills/nestjs.svg",
    alt: "NestJS",
    style: "md:max-h-[30%] md:max-w-[30%] max-h-[10%] max-w-[10%]",
    description: "Framework para Nodejs",
    category: "backend",
  },
  {
    url: "/skills/javascript.svg",
    alt: "Javascript",
    style: "md:max-h-[30%] md:max-w-[30%] max-h-[10%] max-w-[10%]",
    description: "Linguagem de Programação",
    category: "linguagem",
  },
  {
    url: "/skills/python.svg",
    alt: "Python",
    style: "md:max-h-[30%] md:max-w-[30%] max-h-[10%] max-w-[10%]",
    description: "Linguagem de Programação",
    category: "linguagem",
  },
];